swagger: "2.0"
info:
  title: Cyber-fit API
  version: 0.0.1
schemes:
- "https"
paths:
  /athletes:
    get:
      tags:
      - "Athletes"
      summary: "Get all athletes"
      operationId: "getAllAthletes"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Created"
          schema:
            type: array
            items:
              $ref: "#/definitions/Athelete"
          
  /athletes/{athleteId}/workouts:
    post:
      tags:
      - "Workouts"
      summary: "Add a new workout to the athlete"
      operationId: "addWorkout"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: athleteId
        required: true
        type: string
        format: uuid
      - in: "body"
        name: "body"
        description: "Workout object"
        required: true
        schema:
          $ref: "#/definitions/Workout"
      responses:
        "201":
          description: "Created"
          schema:
            $ref: "#/definitions/Workout"
        "400":
          description: "Invalid body"
        "404":
          description: "Athlete with such id not found"
  /workouts/{workoutId}:
    put:
      tags:
      - "Workouts"
      summary: "Update workout"
      operationId: "updateWorkout"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: path
        name: workoutId
        required: true
        type: string
        format: uuid
      - in: "body"
        name: "body"
        description: "Workout object"
        required: true
        schema:
          $ref: "#/definitions/Workout"
      responses:
        "200":
          description: "Updated"
          schema:
            $ref: "#/definitions/Workout"
        "400":
          description: "Invalid body"
        "404":
          description: "Workout with such id not found"
definitions:
  Athelete:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      workouts:
        type: "array"
        items:
          $ref: '#/definitions/Workout'
      name:
        type: "string"
  Workout:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
        readOnly: true
      title:
        type: "string"
      date:
        type: "string"
        format: "date"
      exercises:
        type: "array"
        items:
          $ref: '#/definitions/Exercise'
  Exercise:
    type: "object"
    properties:
      id:
        type: "string"
        format: "uuid"
      title:
        type: "string"
      weight:
        type: "integer"
        format: "int32"
      steps:
        type: "integer"
        format: "int32"
      reps:
        type: "integer"
        format: "int32"
      hasWarmup:
        type: "boolean"
      warmups:
        type: "array"
        items:
          $ref: '#/definitions/Warmup'
  Warmup:
    type: "object"
    properties:
      weight:
        type: "integer"
        format: "int32"
      steps:
        type: "integer"
        format: "int32"
      reps:
        type: "integer"
        format: "int32"
  
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"